import Foundation
import Testing
@testable import VoiceInk

struct TranscriptionOutputFilterTests {
    @Test func transcriptionFilterCleansPauseNoiseAndRepeatedWords() async throws {
        let oldRemoveFillerWords = UserDefaults.standard.object(forKey: "RemoveFillerWords")
        let oldCleanupLevel = UserDefaults.standard.object(forKey: TranscriptionCleanupLevel.userDefaultsKey)
        defer {
            if let oldRemoveFillerWords {
                UserDefaults.standard.set(oldRemoveFillerWords, forKey: "RemoveFillerWords")
            } else {
                UserDefaults.standard.removeObject(forKey: "RemoveFillerWords")
            }
            if let oldCleanupLevel {
                UserDefaults.standard.set(oldCleanupLevel, forKey: TranscriptionCleanupLevel.userDefaultsKey)
            } else {
                UserDefaults.standard.removeObject(forKey: TranscriptionCleanupLevel.userDefaultsKey)
            }
        }

        UserDefaults.standard.set(true, forKey: "RemoveFillerWords")
        TranscriptionCleanupLevel.setCurrent(.polished)

        #expect(TranscriptionOutputFilter.filter("[Model.]") == "Model.")
        #expect(TranscriptionOutputFilter.filter("[inaudible]") == "")
        #expect(TranscriptionOutputFilter.filter("Use [inaudible] now.") == "Use now.")
        #expect(TranscriptionOutputFilter.filter("Use [model] now.") == "Use [model] now.")
        #expect(TranscriptionOutputFilter.filter("Use (model) now.") == "Use (model) now.")
        #expect(TranscriptionOutputFilter.filter("hmm.... eh... I I think think this this works.") == "I think this works.")
        #expect(TranscriptionOutputFilter.filter("mm-hmm... uh-huh, I think so.") == "I think so.")
        #expect(TranscriptionOutputFilter.filter("uh-uh... not that.") == "not that.")
        #expect(TranscriptionOutputFilter.filter("mhmm, this works.") == "this works.")
        #expect(TranscriptionOutputFilter.filter("I was, like, going there.") == "I was going there.")
        #expect(TranscriptionOutputFilter.filter("I was like going there.") == "I was going there.")
        #expect(TranscriptionOutputFilter.filter("We are like almost done.") == "We are almost done.")
        #expect(TranscriptionOutputFilter.filter("You know, this works.") == "this works.")
        #expect(TranscriptionOutputFilter.filter("I mean, this works.") == "this works.")
        #expect(TranscriptionOutputFilter.filter("Like, this works.") == "this works.")
        #expect(TranscriptionOutputFilter.filter("Okay so this works.") == "this works.")
        #expect(TranscriptionOutputFilter.filter("All right, so this works.") == "this works.")
        #expect(TranscriptionOutputFilter.filter("Right so this works.") == "this works.")
        #expect(TranscriptionOutputFilter.filter("Yeah, so this works.") == "this works.")
        #expect(TranscriptionOutputFilter.filter("This works, you know.") == "This works.")
        #expect(TranscriptionOutputFilter.filter("This works you know.") == "This works.")
        #expect(TranscriptionOutputFilter.filter("This works you know what I mean.") == "This works.")
        #expect(TranscriptionOutputFilter.filter("This works, you know what I mean.") == "This works.")
        #expect(TranscriptionOutputFilter.filter("you know.") == "")
        #expect(TranscriptionOutputFilter.filter("you know what I mean.") == "")
        #expect(TranscriptionOutputFilter.filter("I like this model.") == "I like this model.")
        #expect(TranscriptionOutputFilter.filter("This is like magic.") == "This is like magic.")
        #expect(TranscriptionOutputFilter.filter("Do you know this?") == "Do you know this?")
        #expect(TranscriptionOutputFilter.filter("Tell me if you know.") == "Tell me if you know.")
        #expect(TranscriptionOutputFilter.filter("you know?") == "you know?")
        #expect(TranscriptionOutputFilter.filter("You know this already.") == "You know this already.")
        #expect(TranscriptionOutputFilter.filter("I mean business.") == "I mean business.")
        #expect(TranscriptionOutputFilter.filter("Okay, this works.") == "Okay, this works.")
        #expect(TranscriptionOutputFilter.filter("Right, this works.") == "Right, this works.")
        #expect(TranscriptionOutputFilter.filter("Do you know what I mean?") == "Do you know what I mean?")
        #expect(TranscriptionOutputFilter.filter("I know you know.") == "I know you know.")
        #expect(TranscriptionOutputFilter.filter("no no this is fine") == "no no this is fine")
        #expect(TranscriptionOutputFilter.filter("I think this works. I think this works.") == "I think this works.")
        #expect(TranscriptionOutputFilter.filter("Ship the model. ship the model.") == "Ship the model.")
        #expect(TranscriptionOutputFilter.filter("I think I think this works.") == "I think this works.")
        #expect(TranscriptionOutputFilter.filter("We should ship we should ship this.") == "We should ship this.")
        #expect(TranscriptionOutputFilter.filter("I think this works, I think this works.") == "I think this works.")
        #expect(TranscriptionOutputFilter.filter("Ship the model; ship the model.") == "Ship the model.")
        #expect(TranscriptionOutputFilter.filter("Okay. Okay.") == "Okay. Okay.")
        #expect(TranscriptionOutputFilter.filter("I know, I know.") == "I know, I know.")
        #expect(TranscriptionOutputFilter.filter("New York New York is the title.") == "New York New York is the title.")
        #expect(TranscriptionOutputFilter.filter("Hello, comma world.") == "Hello, world.")
        #expect(TranscriptionOutputFilter.filter("Hello, comma, world.") == "Hello, world.")
        #expect(TranscriptionOutputFilter.filter("Hello! exclamation mark.") == "Hello!")
        #expect(TranscriptionOutputFilter.filter("Are you ready? question mark.") == "Are you ready?")
        #expect(TranscriptionOutputFilter.filter(".env file.") == ".env file.")
        #expect(TranscriptionOutputFilter.filter("\"What?\".") == "\"What?\".")
    }

    @Test func insertionPolishUsesCursorContextForMidSentenceFragments() async throws {
        TranscriptionCleanupLevel.setCurrent(.polished)
        let midSentenceContext = TranscriptionOutputFilter.TextInsertionContext(precedingText: "...so this")
        let sentenceStartContext = TranscriptionOutputFilter.TextInsertionContext(precedingText: "Done. ")
        let questionContext = TranscriptionOutputFilter.TextInsertionContext(precedingText: "Done?")
        let exclamationContext = TranscriptionOutputFilter.TextInsertionContext(precedingText: "Done!")
        let colonContext = TranscriptionOutputFilter.TextInsertionContext(precedingText: "Note:")
        let selectedTextContext = TranscriptionOutputFilter.TextInsertionContext(precedingText: "Done?", selectedText: "old")
        let selectedMidSentenceContext = TranscriptionOutputFilter.TextInsertionContext(precedingText: "Use ", selectedText: "old")
        let openParenthesisContext = TranscriptionOutputFilter.TextInsertionContext(precedingText: "(")
        let wordBeforeParenthesisContext = TranscriptionOutputFilter.TextInsertionContext(precedingText: "Use")
        let wordBeforeQuoteContext = TranscriptionOutputFilter.TextInsertionContext(precedingText: "She said")
        let newLineContext = TranscriptionOutputFilter.TextInsertionContext(precedingText: "Done\n")

        #expect(TranscriptionOutputFilter.applyInsertionPolish("Model.", context: midSentenceContext) == "model")
        #expect(TranscriptionOutputFilter.applyInsertionSpacing("model", context: midSentenceContext) == " model")
        #expect(TranscriptionOutputFilter.applyInsertionSpacing("Model", context: questionContext) == " Model")
        #expect(TranscriptionOutputFilter.applyInsertionSpacing("Model", context: exclamationContext) == " Model")
        #expect(TranscriptionOutputFilter.applyInsertionSpacing("model", context: colonContext) == " model")
        #expect(TranscriptionOutputFilter.applyInsertionSpacing("Model", context: selectedTextContext) == "Model")
        #expect(TranscriptionOutputFilter.applyInsertionPolish("Model.", context: selectedMidSentenceContext) == "model")
        #expect(TranscriptionOutputFilter.applyInsertionPolish("Model!", context: midSentenceContext) == "model")
        #expect(TranscriptionOutputFilter.applyInsertionPolish("Model?", context: midSentenceContext) == "model")
        #expect(TranscriptionOutputFilter.applyInsertionPolish("Model -", context: midSentenceContext) == "model")
        #expect(TranscriptionOutputFilter.applyInsertionPolish("Model —", context: midSentenceContext) == "model")
        #expect(TranscriptionOutputFilter.applyInsertionPolish("Model /", context: midSentenceContext) == "model")
        #expect(TranscriptionOutputFilter.applyInsertionPolish("Model \\", context: midSentenceContext) == "model")
        #expect(TranscriptionOutputFilter.applyInsertionPolish("Model |", context: midSentenceContext) == "model")
        #expect(TranscriptionOutputFilter.applyInsertionPolish("... Model.", context: midSentenceContext) == "model")
        #expect(TranscriptionOutputFilter.applyInsertionPolish("— Model.", context: midSentenceContext) == "model")
        #expect(TranscriptionOutputFilter.applyInsertionPolish(": Model.", context: midSentenceContext) == "model")
        #expect(TranscriptionOutputFilter.applyInsertionSpacing("model", context: selectedMidSentenceContext) == "model")
        #expect(TranscriptionOutputFilter.applyInsertionSpacing("model", context: openParenthesisContext) == "model")
        #expect(TranscriptionOutputFilter.applyInsertionSpacing("(model)", context: wordBeforeParenthesisContext) == " (model)")
        #expect(TranscriptionOutputFilter.applyInsertionSpacing("\"hello\"", context: wordBeforeQuoteContext) == " \"hello\"")
        #expect(TranscriptionOutputFilter.applyInsertionSpacing("/users", context: wordBeforeParenthesisContext) == "/users")
        #expect(TranscriptionOutputFilter.applyInsertionPolish("\"Model\".", context: midSentenceContext) == "\"model\"")
        #expect(TranscriptionOutputFilter.applyInsertionPolish("(Model).", context: midSentenceContext) == "(model)")
        #expect(TranscriptionOutputFilter.applyInsertionPolish("{Model}.", context: midSentenceContext) == "{model}")
        #expect(TranscriptionOutputFilter.applyInsertionPolish("\"Model!\"", context: midSentenceContext) == "\"model\"")
        #expect(TranscriptionOutputFilter.applyInsertionPolish("(Model!)", context: midSentenceContext) == "(model)")
        #expect(TranscriptionOutputFilter.applyInsertionPolish("{Model?}", context: midSentenceContext) == "{model}")
        #expect(TranscriptionOutputFilter.applyInsertionPolish("\"Model!\".", context: midSentenceContext) == "\"model\"")
        #expect(TranscriptionOutputFilter.applyInsertionPolish("(Model!).", context: midSentenceContext) == "(model)")
        #expect(TranscriptionOutputFilter.applyInsertionPolish("{Model?}.", context: midSentenceContext) == "{model}")
        #expect(TranscriptionOutputFilter.applyInsertionPolish("[Model.]", context: nil) == "model")
        #expect(TranscriptionOutputFilter.applyInsertionPolish("[Model!]", context: nil) == "model")
        #expect(TranscriptionOutputFilter.applyInsertionPolish("What?", context: midSentenceContext) == "what?")
        #expect(TranscriptionOutputFilter.applyInsertionPolish("\"What?\".", context: midSentenceContext) == "\"what?\"")
        #expect(TranscriptionOutputFilter.applyInsertionPolish("state-of-the-art", context: wordBeforeParenthesisContext) == "state-of-the-art")
        #expect(TranscriptionOutputFilter.applyInsertionPolish("/users", context: wordBeforeParenthesisContext) == "/users")
        #expect(TranscriptionOutputFilter.applyInsertionPolish("docs/", context: wordBeforeParenthesisContext) == "docs/")
        #expect(TranscriptionOutputFilter.applyInsertionPolish(TranscriptionOutputFilter.filter("Open quote model close quote."), context: midSentenceContext) == "\"model\"")
        #expect(TranscriptionOutputFilter.applyInsertionPolish(TranscriptionOutputFilter.filter("Open parenthesis model close parenthesis."), context: midSentenceContext) == "(model)")
        #expect(TranscriptionOutputFilter.applyInsertionPolish("Comma.", context: midSentenceContext) == ",")
        #expect(TranscriptionOutputFilter.applyInsertionSpacing(",", context: midSentenceContext) == ",")
        #expect(TranscriptionOutputFilter.applyInsertionPolish("Question mark.", context: midSentenceContext) == "?")
        #expect(TranscriptionOutputFilter.applyInsertionPolish("Model.", context: sentenceStartContext) == "Model")
        #expect(TranscriptionOutputFilter.applyInsertionPolish("This is good.", context: sentenceStartContext) == "This is good.")
        #expect(TranscriptionOutputFilter.applyInsertionPolish("Comma.", context: sentenceStartContext) == "Comma")
        #expect(TranscriptionOutputFilter.applyInsertionPolish("Model.", context: newLineContext) == "Model")
        #expect(TranscriptionOutputFilter.applyInsertionPolish("Model.", context: nil) == "model")
        #expect(TranscriptionOutputFilter.applyInsertionPolish("This is good.", context: nil) == "This is good.")
        #expect(TranscriptionOutputFilter.applyInsertionPolish("... This is good.", context: nil) == "This is good.")
        #expect(TranscriptionOutputFilter.applyInsertionPolish(".env file.", context: nil) == ".env file.")
        #expect(TranscriptionOutputFilter.applyInsertionPolish("VoiceInk.", context: nil) == "VoiceInk")
    }

    @Test func insertionContextUsesAccessibilityUTF16Offsets() async throws {
        let prefix = "Say 😄 so this"
        let fullText = "\(prefix) model"
        let selectedRange = CFRange(location: prefix.utf16.count, length: 0)

        let context = TranscriptionOutputFilter.insertionContext(
            fromFullText: fullText,
            selectedRange: selectedRange,
            selectedText: nil
        )

        #expect(context.precedingText == prefix)
        #expect(TranscriptionOutputFilter.applyInsertionPolish("Model.", context: context) == "model")
        #expect(TranscriptionOutputFilter.applyInsertionSpacing("model", context: context) == " model")
    }

    @Test func transcriptionFilterRespectsCleanupLevels() async throws {
        let oldRemoveFillerWords = UserDefaults.standard.object(forKey: "RemoveFillerWords")
        let oldCleanupLevel = UserDefaults.standard.object(forKey: TranscriptionCleanupLevel.userDefaultsKey)
        defer {
            if let oldRemoveFillerWords {
                UserDefaults.standard.set(oldRemoveFillerWords, forKey: "RemoveFillerWords")
            } else {
                UserDefaults.standard.removeObject(forKey: "RemoveFillerWords")
            }
            if let oldCleanupLevel {
                UserDefaults.standard.set(oldCleanupLevel, forKey: TranscriptionCleanupLevel.userDefaultsKey)
            } else {
                UserDefaults.standard.removeObject(forKey: TranscriptionCleanupLevel.userDefaultsKey)
            }
        }

        UserDefaults.standard.set(true, forKey: "RemoveFillerWords")

        TranscriptionCleanupLevel.setCurrent(.raw)
        #expect(TranscriptionOutputFilter.filter("hmm... Hello comma world. Hello comma world.") == "hmm... Hello comma world. Hello comma world.")
        #expect(TranscriptionOutputFilter.filter("I can apostrophe t go.") == "I can apostrophe t go.")
        #expect(TranscriptionOutputFilter.filter("Felix apostrophe s laptop.") == "Felix apostrophe s laptop.")
        #expect(TranscriptionOutputFilter.filter("Wrong phrase scratch that. Right phrase.") == "Wrong phrase scratch that. Right phrase.")
        #expect(TranscriptionOutputFilter.filter("Wrong phrase undo that. Right phrase.") == "Wrong phrase undo that. Right phrase.")
        #expect(TranscriptionOutputFilter.filter("Use model replace that with module.") == "Use model replace that with module.")

        TranscriptionCleanupLevel.setCurrent(.light)
        #expect(TranscriptionOutputFilter.filter("hmm... Hello comma world.") == "hmm... Hello, world.")
        #expect(TranscriptionOutputFilter.filter("I can apostrophe t go.") == "I can't go.")
        #expect(TranscriptionOutputFilter.filter("Felix apostrophe s laptop.") == "Felix's laptop.")
        #expect(TranscriptionOutputFilter.filter("Wrong phrase scratch that. Right phrase.") == "Wrong phrase scratch that. Right phrase.")
        #expect(TranscriptionOutputFilter.filter("Wrong phrase undo that. Right phrase.") == "Wrong phrase undo that. Right phrase.")
        #expect(TranscriptionOutputFilter.filter("Use model replace that with module.") == "Use model replace that with module.")
        #expect(TranscriptionOutputFilter.filter("Let's meet at two, wait no, three.") == "Let's meet at two, wait no, three.")
        #expect(TranscriptionOutputFilter.filter("I think I think this works.") == "I think I think this works.")
        #expect(TranscriptionOutputFilter.filter("I think this works, I think this works.") == "I think this works, I think this works.")

        TranscriptionCleanupLevel.setCurrent(.polished)
        #expect(TranscriptionOutputFilter.filter("hmm... Hello comma world.") == "Hello, world.")
        #expect(TranscriptionOutputFilter.filter("Let's meet at two, wait no, three.") == "Let's meet at three.")
        #expect(TranscriptionOutputFilter.filter("I think I think this works.") == "I think this works.")
        #expect(TranscriptionOutputFilter.filter("I think this works, I think this works.") == "I think this works.")
    }

    @Test func transcriptionFilterAppliesBoundedBacktrackingCorrections() async throws {
        TranscriptionCleanupLevel.setCurrent(.polished)
        #expect(TranscriptionOutputFilter.filter("Let's meet at two, wait no, three.") == "Let's meet at three.")
        #expect(TranscriptionOutputFilter.filter("The meeting is on Tuesday, sorry not that, actually Wednesday.") == "The meeting is on Wednesday.")
        #expect(TranscriptionOutputFilter.filter("Use model wait no models.") == "Use models.")
        #expect(TranscriptionOutputFilter.filter("Let's meet at two... actually three.") == "Let's meet at three.")
        #expect(TranscriptionOutputFilter.filter("Let's meet at two, no actually three.") == "Let's meet at three.")
        #expect(TranscriptionOutputFilter.filter("Let's meet at two, actually no, three.") == "Let's meet at three.")
        #expect(TranscriptionOutputFilter.filter("Let's meet at two, never mind, three.") == "Let's meet at three.")
        #expect(TranscriptionOutputFilter.filter("Use model or rather models.") == "Use models.")
        #expect(TranscriptionOutputFilter.filter("Use model, no sorry, module.") == "Use module.")
        #expect(TranscriptionOutputFilter.filter("Use model, sorry I mean module.") == "Use module.")
        #expect(TranscriptionOutputFilter.filter("Set color blue, sorry red.") == "Set color red.")
        #expect(TranscriptionOutputFilter.filter("Use model replace that with module.") == "Use module.")
        #expect(TranscriptionOutputFilter.filter("Set color blue change that to red.") == "Set color red.")
        #expect(TranscriptionOutputFilter.filter("Use old model replace that with new module.") == "Use new module.")
        #expect(TranscriptionOutputFilter.filter("The phrase replace that with is useful.") == "The phrase replace that with is useful.")
        #expect(TranscriptionOutputFilter.filter("The command change that to is useful.") == "The command change that to is useful.")
        #expect(TranscriptionOutputFilter.filter("I actually think this works.") == "I actually think this works.")
        #expect(TranscriptionOutputFilter.filter("I mean this is wrong wait no right.") == "I mean this is right.")
        #expect(TranscriptionOutputFilter.filter("I am sorry this happened.") == "I am sorry this happened.")
        #expect(TranscriptionOutputFilter.filter("Never mind what I said.") == "Never mind what I said.")
        #expect(TranscriptionOutputFilter.filter("Wrong phrase scratch that. Right phrase.") == "Right phrase.")
        #expect(TranscriptionOutputFilter.filter("Keep this. Wrong phrase scratch that. Next sentence.") == "Keep this. Next sentence.")
        #expect(TranscriptionOutputFilter.filter("Wrong phrase cancel that. Right phrase.") == "Right phrase.")
        #expect(TranscriptionOutputFilter.filter("Wrong phrase disregard that. Right phrase.") == "Right phrase.")
        #expect(TranscriptionOutputFilter.filter("Wrong phrase delete that. Right phrase.") == "Right phrase.")
        #expect(TranscriptionOutputFilter.filter("Wrong phrase undo that. Right phrase.") == "Right phrase.")
        #expect(TranscriptionOutputFilter.filter("Wrong phrase strike that. Right phrase.") == "Right phrase.")
        #expect(TranscriptionOutputFilter.filter("Use model scratch that modules.") == "Use modules.")
        #expect(TranscriptionOutputFilter.filter("Use old model delete last word module.") == "Use old module.")
        #expect(TranscriptionOutputFilter.filter("Use old model delete the last word module.") == "Use old module.")
        #expect(TranscriptionOutputFilter.filter("Use old model delete previous word module.") == "Use old module.")
        #expect(TranscriptionOutputFilter.filter("Use old model delete that word module.") == "Use old module.")
        #expect(TranscriptionOutputFilter.filter("Use old model undo this word module.") == "Use old module.")
        #expect(TranscriptionOutputFilter.filter("Use old wrong model delete last two words module.") == "Use old module.")
        #expect(TranscriptionOutputFilter.filter("Use old wrong model undo the previous two words module.") == "Use old module.")
        #expect(TranscriptionOutputFilter.filter("Use old wrong model undo previous three words module.") == "Use module.")
        #expect(TranscriptionOutputFilter.filter("Use old wrong model delete last 2 words module.") == "Use old module.")
        #expect(TranscriptionOutputFilter.filter("Use model delete last word.") == "Use")
        #expect(TranscriptionOutputFilter.filter("Use old model delete last two words.") == "Use")
        #expect(TranscriptionOutputFilter.filter("First sentence. Wrong sentence. delete last sentence. Right sentence.") == "First sentence. Right sentence.")
        #expect(TranscriptionOutputFilter.filter("First sentence. Wrong sentence. remove the previous sentence. Right sentence.") == "First sentence. Right sentence.")
        #expect(TranscriptionOutputFilter.filter("First sentence. Wrong sentence. delete that sentence. Right sentence.") == "First sentence. Right sentence.")
        #expect(TranscriptionOutputFilter.filter("First sentence. Wrong sentence. undo this sentence. Right sentence.") == "First sentence. Right sentence.")
        #expect(TranscriptionOutputFilter.filter("Delete that file.") == "Delete that file.")
        #expect(TranscriptionOutputFilter.filter("Undo that change.") == "Undo that change.")
        #expect(TranscriptionOutputFilter.filter("Strike that from the record.") == "Strike that from the record.")
        #expect(TranscriptionOutputFilter.filter("The delete last word shortcut is useful.") == "The delete last word shortcut is useful.")
        #expect(TranscriptionOutputFilter.filter("The delete the last word shortcut is useful.") == "The delete the last word shortcut is useful.")
        #expect(TranscriptionOutputFilter.filter("The delete last two words shortcut is useful.") == "The delete last two words shortcut is useful.")
        #expect(TranscriptionOutputFilter.filter("The delete that word shortcut is useful.") == "The delete that word shortcut is useful.")
        #expect(TranscriptionOutputFilter.filter("Explain how to remove this word from docs.") == "Explain how to remove this word from docs.")
        #expect(TranscriptionOutputFilter.filter("The delete last sentence command is useful.") == "The delete last sentence command is useful.")
        #expect(TranscriptionOutputFilter.filter("Explain how to remove the previous sentence from docs.") == "Explain how to remove the previous sentence from docs.")
        #expect(TranscriptionOutputFilter.filter("The delete that sentence command is useful.") == "The delete that sentence command is useful.")
        #expect(TranscriptionOutputFilter.filter("Explain how to remove this sentence from docs.") == "Explain how to remove this sentence from docs.")
        #expect(TranscriptionOutputFilter.filter("Scratch that itch.") == "Scratch that itch.")
        #expect(TranscriptionOutputFilter.filter("Scratch that.") == "Scratch that.")
        #expect(TranscriptionOutputFilter.filter("Cancel that meeting.") == "Cancel that meeting.")
        #expect(TranscriptionOutputFilter.filter("Disregard that warning.") == "Disregard that warning.")
    }

    @Test func transcriptionFilterAppliesSpokenFormattingCommands() async throws {
        TranscriptionCleanupLevel.setCurrent(.polished)
        #expect(TranscriptionOutputFilter.filter("First line new line second line.") == "First line\nsecond line.")
        #expect(TranscriptionOutputFilter.filter("First line new line wrong line delete last line right line.") == "First line\nright line.")
        #expect(TranscriptionOutputFilter.filter("First line new line wrong line delete the previous line right line.") == "First line\nright line.")
        #expect(TranscriptionOutputFilter.filter("First line new line wrong line delete that line right line.") == "First line\nright line.")
        #expect(TranscriptionOutputFilter.filter("First line press enter wrong line undo previous line right line.") == "First line\nright line.")
        #expect(TranscriptionOutputFilter.filter("First line press enter wrong line undo this line right line.") == "First line\nright line.")
        #expect(TranscriptionOutputFilter.filter("Intro new paragraph Details.") == "Intro\n\nDetails.")
        #expect(TranscriptionOutputFilter.filter("Intro new paragraph wrong paragraph delete last paragraph right paragraph.") == "Intro\n\nright paragraph.")
        #expect(TranscriptionOutputFilter.filter("Intro new paragraph wrong paragraph remove the previous paragraph right paragraph.") == "Intro\n\nright paragraph.")
        #expect(TranscriptionOutputFilter.filter("Intro new paragraph wrong paragraph delete that paragraph right paragraph.") == "Intro\n\nright paragraph.")
        #expect(TranscriptionOutputFilter.filter("Intro skip a line Details.") == "Intro\n\nDetails.")
        #expect(TranscriptionOutputFilter.filter("Intro skip a line wrong paragraph undo previous paragraph right paragraph.") == "Intro\n\nright paragraph.")
        #expect(TranscriptionOutputFilter.filter("Intro skip a line wrong paragraph undo this paragraph right paragraph.") == "Intro\n\nright paragraph.")
        #expect(TranscriptionOutputFilter.filter("Intro start a new paragraph Details.") == "Intro\n\nDetails.")
        #expect(TranscriptionOutputFilter.filter("Intro break here Details.") == "Intro\n\nDetails.")
        #expect(TranscriptionOutputFilter.filter("Intro split here Details.") == "Intro\n\nDetails.")
        #expect(TranscriptionOutputFilter.filter("First thing new sentence second thing.") == "First thing. Second thing.")
        #expect(TranscriptionOutputFilter.filter("First thing next sentence API stays uppercase.") == "First thing. API stays uppercase.")
        #expect(TranscriptionOutputFilter.filter("First press enter second.") == "First\nsecond.")
        #expect(TranscriptionOutputFilter.filter("First hit return key second.") == "First\nsecond.")
        #expect(TranscriptionOutputFilter.filter("Column one press tab column two.") == "Column one\tcolumn two.")
        #expect(TranscriptionOutputFilter.filter("Column one hit tab key column two.") == "Column one\tcolumn two.")
        #expect(TranscriptionOutputFilter.filter("Todo new line bullet point first item new line bullet point second item.") == "Todo\n- first item\n- second item")
        #expect(TranscriptionOutputFilter.filter("Shopping list 1. Apples 2. Bananas 3. Oranges.") == "Shopping list\n1. Apples\n2. Bananas\n3. Oranges.")
        #expect(TranscriptionOutputFilter.filter("My top goals are one finish the report two send the slides.") == "My top goals are\n1. finish the report\n2. send the slides.")
        #expect(TranscriptionOutputFilter.filter("Plan first confirm scope second ship patch.") == "Plan\n1. confirm scope\n2. ship patch.")
        #expect(TranscriptionOutputFilter.filter("Rank 1. Apples only.") == "Rank 1. Apples only.")
        #expect(TranscriptionOutputFilter.filter("Use version 1.2.3 today.") == "Use version 1.2.3 today.")
        #expect(TranscriptionOutputFilter.filter("Use version one two today.") == "Use version one two today.")
        #expect(TranscriptionOutputFilter.filter("The first item is setup. The second item is launch.") == "The first item is setup. The second item is launch.")
        #expect(TranscriptionOutputFilter.filter("Use chat no space GPT today.") == "Use chatGPT today.")
        #expect(TranscriptionOutputFilter.filter("Use happy no space f no space coding.") == "Use happyfcoding.")
        #expect(TranscriptionOutputFilter.filter("There is no space here.") == "There is no space here.")
        #expect(TranscriptionOutputFilter.filter("I want no spaces here.") == "I want no spaces here.")
        #expect(TranscriptionOutputFilter.filter("The no space command is useful.") == "The no space command is useful.")
        #expect(TranscriptionOutputFilter.filter("The delete last line command is useful.") == "The delete last line command is useful.")
        #expect(TranscriptionOutputFilter.filter("The delete last paragraph command is useful.") == "The delete last paragraph command is useful.")
        #expect(TranscriptionOutputFilter.filter("Explain how to undo the previous line in docs.") == "Explain how to undo the previous line in docs.")
        #expect(TranscriptionOutputFilter.filter("Explain how to remove the previous paragraph from docs.") == "Explain how to remove the previous paragraph from docs.")
        #expect(TranscriptionOutputFilter.filter("The delete that line command is useful.") == "The delete that line command is useful.")
        #expect(TranscriptionOutputFilter.filter("Explain how to remove this paragraph from docs.") == "Explain how to remove this paragraph from docs.")
        #expect(TranscriptionOutputFilter.filter("The phrase skip a line is useful.") == "The phrase skip a line is useful.")
        #expect(TranscriptionOutputFilter.filter("Explain how to start a new paragraph in docs.") == "Explain how to start a new paragraph in docs.")
        #expect(TranscriptionOutputFilter.filter("The break here is intentional.") == "The break here is intentional.")
        #expect(TranscriptionOutputFilter.filter("The new sentence command is useful.") == "The new sentence command is useful.")
        #expect(TranscriptionOutputFilter.filter("Explain how to start a new sentence in docs.") == "Explain how to start a new sentence in docs.")
        #expect(TranscriptionOutputFilter.filter("The press enter shortcut is useful.") == "The press enter shortcut is useful.")
        #expect(TranscriptionOutputFilter.filter("Explain how to press enter in docs.") == "Explain how to press enter in docs.")
        #expect(TranscriptionOutputFilter.filter("The press tab shortcut is useful.") == "The press tab shortcut is useful.")
        #expect(TranscriptionOutputFilter.filter("Explain how to press tab in docs.") == "Explain how to press tab in docs.")
        #expect(TranscriptionOutputFilter.filter("Heading one project status.") == "# project status")
        #expect(TranscriptionOutputFilter.filter("Intro new line heading two details.") == "Intro\n## details")
        #expect(TranscriptionOutputFilter.filter("Todo buy milk.") == "- [ ] buy milk")
        #expect(TranscriptionOutputFilter.filter("Checked checkbox send email.") == "- [x] send email")
        #expect(TranscriptionOutputFilter.filter("Inline code user underscore id.") == "`user_id`")
        #expect(TranscriptionOutputFilter.filter("Use inline code user underscore id.") == "Use `user_id`.")
        #expect(TranscriptionOutputFilter.filter("Use inline code user underscore id in the docs.") == "Use `user_id` in the docs.")
        #expect(TranscriptionOutputFilter.filter("Write inline code api slash users for the example.") == "Write `api/users` for the example.")
        #expect(TranscriptionOutputFilter.filter("Link docs to docs dot example dot com.") == "[docs](docs.example.com)")
        #expect(TranscriptionOutputFilter.filter("Markdown link VoiceInk docs to docs dot example dot com slash api.") == "[VoiceInk docs](docs.example.com/api)")
        #expect(TranscriptionOutputFilter.filter("Link docs to docs dot example dot com in the readme.") == "[docs](docs.example.com) in the readme.")
        #expect(TranscriptionOutputFilter.filter("Markdown link VoiceInk docs to docs dot example dot com slash api for the issue.") == "[VoiceInk docs](docs.example.com/api) for the issue.")
        #expect(TranscriptionOutputFilter.filter("Open code block swift new line let x equals one new line close code block") == "```swift\nlet x equals one\n```")
        #expect(TranscriptionOutputFilter.filter("Task force meeting.") == "Task force meeting.")
        #expect(TranscriptionOutputFilter.filter("Heading one is common.") == "Heading one is common.")
        #expect(TranscriptionOutputFilter.filter("Inline code is useful.") == "Inline code is useful.")
        #expect(TranscriptionOutputFilter.filter("Link building to product.") == "Link building to product.")
        #expect(TranscriptionOutputFilter.filter("This newlineish word should stay.") == "This newlineish word should stay.")
    }

    @Test func transcriptionFilterAppliesSpokenEnclosureCommands() async throws {
        TranscriptionCleanupLevel.setCurrent(.polished)
        #expect(TranscriptionOutputFilter.filter("She said open quote hello close quote.") == "She said \"hello\".")
        #expect(TranscriptionOutputFilter.filter("Open quote hello comma world close quote.") == "\"hello, world\".")
        #expect(TranscriptionOutputFilter.filter("Quote hello comma world unquote.") == "\"hello, world\".")
        #expect(TranscriptionOutputFilter.filter("Single quote hello comma world single quote.") == "'hello, world'.")
        #expect(TranscriptionOutputFilter.filter("Put model in parentheses.") == "(model).")
        #expect(TranscriptionOutputFilter.filter("Put model in brackets.") == "[model].")
        #expect(TranscriptionOutputFilter.filter("Wrap user id in braces.") == "{user id}.")
        #expect(TranscriptionOutputFilter.filter("Put hello comma world in quotes.") == "\"hello, world\".")
        #expect(TranscriptionOutputFilter.filter("Use open parenthesis model close parenthesis now.") == "Use (model) now.")
        #expect(TranscriptionOutputFilter.filter("Use open bracket model close bracket now.") == "Use [model] now.")
        #expect(TranscriptionOutputFilter.filter("Use open brace user id colon one close brace now.") == "Use {user id: one} now.")
        #expect(TranscriptionOutputFilter.filter("The quote field stays.") == "The quote field stays.")
        #expect(TranscriptionOutputFilter.filter("Quote from the docs.") == "Quote from the docs.")
        #expect(TranscriptionOutputFilter.filter("The value in parentheses is optional.") == "The value in parentheses is optional.")
    }

    @Test func transcriptionFilterAppliesGuardedSpokenSymbolCommands() async throws {
        TranscriptionCleanupLevel.setCurrent(.polished)
        #expect(TranscriptionOutputFilter.filter("Use api slash users.") == "Use api/users.")
        #expect(TranscriptionOutputFilter.filter("Use model hyphen beta.") == "Use model-beta.")
        #expect(TranscriptionOutputFilter.filter("Use path backslash temp.") == "Use path\\temp.")
        #expect(TranscriptionOutputFilter.filter("Email felix at sign example dot com.") == "Email felix@example.com.")
        #expect(TranscriptionOutputFilter.filter("Set user underscore id.") == "Set user_id.")
        #expect(TranscriptionOutputFilter.filter("Open docs dot example dot com.") == "Open docs.example.com.")
        #expect(TranscriptionOutputFilter.filter("Open https colon slash slash docs dot example dot com slash api.") == "Open https://docs.example.com/api")
        #expect(TranscriptionOutputFilter.filter("Open https colon slash slash docs dot example dot com then click.") == "Open https://docs.example.com then click.")
        #expect(TranscriptionOutputFilter.filter("Use h t t p colon slash slash localhost colon 3000 slash api.") == "Use http://localhost:3000/api")
        #expect(TranscriptionOutputFilter.filter("Open www dot example dot com.") == "Open www.example.com")
        #expect(TranscriptionOutputFilter.filter("Open www dot example dot com slash docs then read.") == "Open www.example.com/docs then read.")
        #expect(TranscriptionOutputFilter.filter("Wait ellipsis maybe.") == "Wait... maybe.")
        #expect(TranscriptionOutputFilter.filter("Wait dot dot dot maybe.") == "Wait... maybe.")
        #expect(TranscriptionOutputFilter.filter("Wait em dash maybe.") == "Wait — maybe.")
        #expect(TranscriptionOutputFilter.filter("Use the slash command.") == "Use the slash command.")
        #expect(TranscriptionOutputFilter.filter("Add a dash of salt.") == "Add a dash of salt.")
        #expect(TranscriptionOutputFilter.filter("Use model dash name.") == "Use model-name.")
        #expect(TranscriptionOutputFilter.filter("Use the at sign symbol.") == "Use the at sign symbol.")
        #expect(TranscriptionOutputFilter.filter("Use the dot product.") == "Use the dot product.")
        #expect(TranscriptionOutputFilter.filter("Use dot notation.") == "Use dot notation.")
        #expect(TranscriptionOutputFilter.filter("Show dot file behavior.") == "Show dot file behavior.")
        #expect(TranscriptionOutputFilter.filter("Please at sign up tomorrow.") == "Please at sign up tomorrow.")
        #expect(TranscriptionOutputFilter.filter("Use the underscore command.") == "Use the underscore command.")
        #expect(TranscriptionOutputFilter.filter("We discussed http colon syntax today.") == "We discussed http colon syntax today.")
        #expect(TranscriptionOutputFilter.filter("Say www dot matrix is old.") == "Say www dot matrix is old.")
    }

    @Test func transcriptionFilterAppliesGuardedSpokenContractions() async throws {
        TranscriptionCleanupLevel.setCurrent(.polished)
        #expect(TranscriptionOutputFilter.filter("I can apostrophe t go.") == "I can't go.")
        #expect(TranscriptionOutputFilter.filter("I don apostrophe t know.") == "I don't know.")
        #expect(TranscriptionOutputFilter.filter("I apostrophe m ready.") == "I'm ready.")
        #expect(TranscriptionOutputFilter.filter("We apostrophe re live.") == "We're live.")
        #expect(TranscriptionOutputFilter.filter("They apostrophe ve shipped.") == "They've shipped.")
        #expect(TranscriptionOutputFilter.filter("It apostrophe s ready.") == "It's ready.")
        #expect(TranscriptionOutputFilter.filter("She apostrophe ll approve.") == "She'll approve.")
        #expect(TranscriptionOutputFilter.filter("Let apostrophe s ship.") == "Let's ship.")
        #expect(TranscriptionOutputFilter.filter("The word apostrophe is here.") == "The word apostrophe is here.")
    }

    @Test func transcriptionFilterAppliesGuardedSpokenPossessives() async throws {
        TranscriptionCleanupLevel.setCurrent(.polished)
        #expect(TranscriptionOutputFilter.filter("Felix apostrophe s laptop is ready.") == "Felix's laptop is ready.")
        #expect(TranscriptionOutputFilter.filter("The project apostrophe s status changed.") == "The project's status changed.")
        #expect(TranscriptionOutputFilter.filter("Use API apostrophe s response.") == "Use API's response.")
        #expect(TranscriptionOutputFilter.filter("Apostrophe s is a suffix.") == "Apostrophe s is a suffix.")
        #expect(TranscriptionOutputFilter.filter("The suffix apostrophe s is common.") == "The suffix apostrophe s is common.")
        #expect(TranscriptionOutputFilter.filter("Use apostrophe s symbol.") == "Use apostrophe s symbol.")
    }

    @Test func transcriptionFilterAppliesGuardedCodeCaseCommands() async throws {
        TranscriptionCleanupLevel.setCurrent(.polished)
        #expect(TranscriptionOutputFilter.filter("Use all caps api key.") == "Use API KEY.")
        #expect(TranscriptionOutputFilter.filter("Please uppercase urgent.") == "Please URGENT.")
        #expect(TranscriptionOutputFilter.filter("Use lowercase VoiceInk.") == "Use voiceink.")
        #expect(TranscriptionOutputFilter.filter("Use capitalize felix.") == "Use Felix.")
        #expect(TranscriptionOutputFilter.filter("Use title case weekly report.") == "Use Weekly Report.")
        #expect(TranscriptionOutputFilter.filter("All caps is loud.") == "All caps is loud.")
        #expect(TranscriptionOutputFilter.filter("The all caps command is useful.") == "The all caps command is useful.")
        #expect(TranscriptionOutputFilter.filter("I prefer lowercase VoiceInk.") == "I prefer lowercase VoiceInk.")
        #expect(TranscriptionOutputFilter.filter("Use camel case user id.") == "Use userId.")
        #expect(TranscriptionOutputFilter.filter("Set variable snake case user id.") == "Set variable user_id.")
        #expect(TranscriptionOutputFilter.filter("Use kebab case user id.") == "Use user-id.")
        #expect(TranscriptionOutputFilter.filter("Use pascal case user profile.") == "Use UserProfile.")
        #expect(TranscriptionOutputFilter.filter("Use camel case API key.") == "Use apiKey.")
        #expect(TranscriptionOutputFilter.filter("Use camel case user id in the request.") == "Use userId in the request.")
        #expect(TranscriptionOutputFilter.filter("Set variable snake case user id for the payload.") == "Set variable user_id for the payload.")
        #expect(TranscriptionOutputFilter.filter("Camel case is common.") == "Camel case is common.")
        #expect(TranscriptionOutputFilter.filter("Use camel case for variable names.") == "Use camel case for variable names.")
        #expect(TranscriptionOutputFilter.filter("I prefer snake case user id.") == "I prefer snake case user id.")
    }

    @Test func transcriptionFilterAppliesGuardedValueFormatting() async throws {
        TranscriptionCleanupLevel.setCurrent(.polished)
        #expect(TranscriptionOutputFilter.filter("Meet on June second 2026.") == "Meet on June 2, 2026.")
        #expect(TranscriptionOutputFilter.filter("Meet on June 2 2026.") == "Meet on June 2, 2026.")
        #expect(TranscriptionOutputFilter.filter("Meet on June 2nd.") == "Meet on June 2.")
        #expect(TranscriptionOutputFilter.filter("Meet on june 2.") == "Meet on June 2.")
        #expect(TranscriptionOutputFilter.filter("Meet on june second.") == "Meet on June 2.")
        #expect(TranscriptionOutputFilter.filter("Meet on September twenty first.") == "Meet on September 21.")
        #expect(TranscriptionOutputFilter.filter("Meet on May second.") == "Meet on May 2.")
        #expect(TranscriptionOutputFilter.filter("Call at 9 30 a m.") == "Call at 9:30 AM.")
        #expect(TranscriptionOutputFilter.filter("Call at 7 p m.") == "Call at 7 PM.")
        #expect(TranscriptionOutputFilter.filter("Pay 20 dollars today.") == "Pay $20 today.")
        #expect(TranscriptionOutputFilter.filter("Send dollar sign 19.99 now.") == "Send $19.99 now.")
        #expect(TranscriptionOutputFilter.filter("Budget 30 euros and 20 pounds.") == "Budget €30 and £20.")
        #expect(TranscriptionOutputFilter.filter("Progress is 85 percent done.") == "Progress is 85% done.")
        #expect(TranscriptionOutputFilter.filter("Pay twenty dollars today.") == "Pay $20 today.")
        #expect(TranscriptionOutputFilter.filter("Budget thirty euros and twenty pounds.") == "Budget €30 and £20.")
        #expect(TranscriptionOutputFilter.filter("Progress is eighty five percent done.") == "Progress is 85% done.")
        #expect(TranscriptionOutputFilter.filter("Version two point zero shipped.") == "Version 2.0 shipped.")
        #expect(TranscriptionOutputFilter.filter("The score is four point six today.") == "The score is 4.6 today.")
        #expect(TranscriptionOutputFilter.filter("The dollar sign is confusing.") == "The dollar sign is confusing.")
        #expect(TranscriptionOutputFilter.filter("I may second that idea.") == "I may second that idea.")
        #expect(TranscriptionOutputFilter.filter("We march first then rest.") == "We march first then rest.")
        #expect(TranscriptionOutputFilter.filter("I may 2 of those.") == "I may 2 of those.")
        #expect(TranscriptionOutputFilter.filter("March 42 is invalid.") == "March 42 is invalid.")
        #expect(TranscriptionOutputFilter.filter("I lost 20 pounds.") == "I lost 20 pounds.")
        #expect(TranscriptionOutputFilter.filter("Use 20 pounds of flour.") == "Use 20 pounds of flour.")
        #expect(TranscriptionOutputFilter.filter("I lost twenty pounds.") == "I lost twenty pounds.")
        #expect(TranscriptionOutputFilter.filter("Use twenty pounds of flour.") == "Use twenty pounds of flour.")
        #expect(TranscriptionOutputFilter.filter("One point to remember.") == "One point to remember.")
        #expect(TranscriptionOutputFilter.filter("Use 13 99 p m as a test.") == "Use 13 99 p m as a test.")
    }

    @Test func transcriptionFilterRemovesCommonASRBoilerplate() async throws {
        TranscriptionCleanupLevel.setCurrent(.polished)
        #expect(TranscriptionOutputFilter.filter("Thank you for watching.") == "")
        #expect(TranscriptionOutputFilter.filter("Okay. Thank you for watching.") == "Okay.")
        #expect(TranscriptionOutputFilter.filter("Ship it.\nSubtitles by Amara.org community") == "Ship it.")
        #expect(TranscriptionOutputFilter.filter("Thank you for helping.") == "Thank you for helping.")
        #expect(TranscriptionOutputFilter.filter("End with thank you for watching.") == "End with thank you for watching.")
    }

    @Test func transcriptionFilterAppliesConservativeSpokenPunctuationCommands() async throws {
        TranscriptionCleanupLevel.setCurrent(.polished)
        #expect(TranscriptionOutputFilter.filter("Hello comma world full stop") == "Hello, world.")
        #expect(TranscriptionOutputFilter.filter("Hello comma, world.") == "Hello, world.")
        #expect(TranscriptionOutputFilter.filter("Are you coming question mark") == "Are you coming?")
        #expect(TranscriptionOutputFilter.filter("Are you coming question point") == "Are you coming?")
        #expect(TranscriptionOutputFilter.filter("Are you coming question sign") == "Are you coming?")
        #expect(TranscriptionOutputFilter.filter("Are you coming question mark. I am waiting.") == "Are you coming? I am waiting.")
        #expect(TranscriptionOutputFilter.filter("Ship it exclamation mark") == "Ship it!")
        #expect(TranscriptionOutputFilter.filter("Ship it exclamation sign") == "Ship it!")
        #expect(TranscriptionOutputFilter.filter("Ship it exclamation mark.") == "Ship it!")
        #expect(TranscriptionOutputFilter.filter("Use model semicolon retry colon now") == "Use model; retry: now")
        #expect(TranscriptionOutputFilter.filter("The question mark command is useful.") == "The question mark command is useful.")
        #expect(TranscriptionOutputFilter.filter("The exclamation sign command is useful.") == "The exclamation sign command is useful.")
        #expect(TranscriptionOutputFilter.filter("The colon operator is useful.") == "The colon operator is useful.")
        #expect(TranscriptionOutputFilter.filter("The ellipsis symbol is useful.") == "The ellipsis symbol is useful.")
        #expect(TranscriptionOutputFilter.filter("This is a trial period") == "This is a trial period")
        #expect(TranscriptionOutputFilter.filter("Use the Oxford comma") == "Use the Oxford comma")
    }
}
